name: MacOS_Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.11.5]
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Xcode Deps
      run: brew install coreutils &&
           echo "$CERTIFICATES_P12" > cert.txt &&
           echo "$CERTIFICATES_PROFILE" > profile.txt &&
           gbase64 -di cert.txt > cert.p12 &&
           gbase64 -di profile.txt > profile.mobileprovision &&
           KEYCHAIN_PATH=$RUNNER_TEMP/login.keychain

    - name: Install dependencies
      run: |
        pip install -e '.[test]'

    - name: Pre Run Environment state
      run: python test_install/prerun.py

    - name: install java
      run: pyflutterinstall --only-java -y

    - name: which java
      run: setenvironment refresh "which java"
      
    # Just so you know, this is the biggest hack ever to bring in env vars.
    - name: Test java is 17
      run: setenvironment refresh "python test_install/is_java_version.py 20"

    - name: install android
      run: setenvironment refresh "python -m pyflutterinstall.install.android_sdk"

    - name: install ant
      run: setenvironment refresh "python -m pyflutterinstall.install.ant_sdk"

    - name: install gradle
      run: setenvironment refresh "python -m pyflutterinstall.install.gradle"

    - name: install flutter
      run: setenvironment refresh "python -m pyflutterinstall.install.flutter_sdk"

    - name: post install check
      run: setenvironment refresh "python -m pyflutterinstall.postrun"

    - name: Print Flutter SDK Folder
      run: setenvironment refresh "python test_install/print_flutter_folder.py"
